postgres:
  username: user
  password: init1234
  dbName: contapics
  storage: 10Gi
  storageClass: gp2
  image: postgres:14
  replicas: 1

backend:
  image: 601094796288.dkr.ecr.eu-central-1.amazonaws.com/backend:latest
  replicas: 1
  port: 8080
  env:
    springProfile: docker
    corsOrigin: "http://frontend.contapics.local"
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

frontend:
  image: 601094796288.dkr.ecr.eu-central-1.amazonaws.com/frontend:latest
  replicas: 1
  port: 80
  resources:
    requests:
      cpu: 100m
      memory: 50Mi
    limits:
      cpu: 200m
      memory: 100Mi
  backendUrl: "http://backend.contapics.local/api"

ingress:
  enabled: true
  frontendHost: frontend.contapics.local
  backendHost: backend.contapics.local

grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
    hosts:
      - grafana.contapics.local
    path: /